type Mutation {
  placeSingleCall(
    agentId: String!
    leadId: String!
  ): PlaceSingleCallOutput
  placeBulkCall(
    agentId: String!
    leads: [BulkLeadInput!]!
  ): PlaceBulkCallOutput
}

input BulkLeadInput {
  phoneNumber: String!
  name: String
  email: String
  companyName: String
}

type PlaceSingleCallOutput {
  success: Boolean!
  executionId: String
  message: String
}

type PlaceBulkCallOutput {
  success: Boolean!
  totalRequested: Int!
  totalPlaced: Int!
  totalSkipped: Int!
  message: String
}


